#!/usr/bin/env python
# -*- coding: utf-8 -*-
from tkinter import *


def separaPal(text):
    strBuffer = ""
    lstPalavras = []
    
    for i in range(len(text)):
        #Se o caractere for 0-9 ou a-z
        if text[i].isalnum():
            strBuffer += text[i] #Adiciona no buffer para formar palavra
        else:
            #Se o strBuffer formado for maior que 0
            if len(strBuffer) > 0:
                if text[i] == '-':
                    #Se o ultimo caractere do strBuffer nao for um hifen
                    if strBuffer[-1] != '-':
                        strBuffer += text[i] #Entao é adicionado o hifen ao buffer
                    else: #Se for..
                        lstPalavras.append(strBuffer[:-1]) #Entao adiciona somente a palavra sem o hifen a lista
                        strBuffer = ''
                else:
                    lstPalavras.append(strBuffer)
                    strBuffer = ''
    if len(strBuffer) > 0:
        lstPalavras.append(strBuffer)
    
    return lstPalavras

def getLog(string):
	
	txt = open("C:\\Users\\20171bsi0464\\Desktop\\biblia.txt","rt")
	linha = txt.readline()
	i = 1
	string = string.lower()
	while(linha != ""):
		linha = txt.readline()
		
		linha = linha.lower()
		
		if(string in separaPal(linha)):
			dic = {string : i }
			dic.update(dic)
			i = i + 1
	try:
		print(dic)
	except Exception:
		print(string + " 0")
		pass
	txt.close()
	
    
    #return dataCompleta



master = Tk()
w = Label(master, text="Digite a palavra:")
w.pack()
e1 = Entry(master)
e1.pack()
b = Button(master, text="OK", command=lambda: getLog(e1.get()))
b.pack()

#listbox = Listbox(master)
#listbox.pack()

#data = getLog()
#i = 0
#for item in data:
#    listbox.insert(END, item)
#    i += 1
#w = Label(master, text="Desligado" + str(i) + " vezes")
#w.pack()

mainloop()
diabo = 31
demonio = 59


